- hosts: 
    zabbix_agents

  tasks:

#configure zabbix repo

    - name: Zabbix | Make sure the ansible required dependencies are installed
      become: yes
      apt:
        pkg: python-pycurl
        state: present
  
    - name: Zabbix | {{ ansible_distribution }} | General | Get Zabbix repository
      get_url:
        url: "http://repo.zabbix.com/zabbix/{{ zabbix_install_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_install_version }}-1+{{ ansible_distribution_release }}_all.deb"
        dest: /tmp
     
    - name: Zabbix | {{ ansible_distribution }} | General | Add Zabbix repo
      become: yes
      apt:
        deb: "/tmp/zabbix-release_{{ zabbix_install_version }}-1+{{ ansible_distribution_release }}_all.deb"
        state: present
     
    - name: Zabbix | {{ ansible_distribution }} | General | Update apt cache with new repo data
      become: yes
      apt:
        update_cache: yes

# install agent

    - name: Zabbix | {{ ansible_distribution }} | Make sure Zabbix agent is installed
      become: yes
      apt:
        pkg: zabbix-agent
        state: present
      notify: 'Start agent'

# start service 

  handlers:
    - name: Zabbix | Start agent service
      listen: 'Start agent'
      service:
        name: 'zabbix-agent'
        state: started


